version: '3.8'

services:
  goof:
    build: .
    container_name: goof
    environment:
      - DOCKER=1
      - MYSQL_HOST=goof-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=acme
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MONGO_URL=mongodb://goof-mongo:27017/express-todo
      - JENKINS_URL=http://jenkins:8080
    ports:
      - "3001:3001"
      - "9229:9229"  # Debug port (optional)
    depends_on:
      goof-mysql:
        condition: service_healthy
      goof-mongo:
        condition: service_healthy
    command: ["./wait-for-it.sh", "goof-mysql:3306", "--timeout=60", "--strict", "--", "npm", "start"]
    networks:
      - goofnet

  goof-mysql:
    container_name: goof-mysql
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=acme
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - goofnet

    goof-mongo:
    container_name: goof-mongo
    image: mongo:4.4
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - goofnet

networks:
  goofnet:
    driver: bridge
