version: "2"
services:
  goof:
    build: .
    container_name: goof
    environment:
      - DOCKER=1
      - MYSQL_HOST=goof-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=acme
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MONGO_URL=mongodb://goof-mongo:27017/express-todo
    ports:
      - "3001:3001"
      - "9229:9229"
    links:
      - goof-mongo
      - goof-mysql
    depends_on:
      - goof-mongo
      - goof-mysql

  goof-mongo:
    container_name: goof-mongo
    image: mongo:3
    ports:
      - "27017:27017"

  goof-mysql:
    container_name: goof-mysql
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acme
    ports:
      - "3306:3306"

